### ISSUE TITLE
v0.6.0 Cloned statement doesn't have postgres methods

### ISSUE THREAD

**Issue by FanFataL** [Suor/sql-bricks-postgres#21]
Hi,

After upgrading from `0.5.0` into `0.6.0` cloned statements stops working.

Steps to reproduce:
```
const query = sql.select().from('user');
query.limit(10); // <--- this is working
const query2 = query.clone();
query2.limit(10); // <--- this not working in 0.6.0 (limit is not a function)
```

Probably upgrading sqlBricks to v3 makes this issue.

**Comment by Suor** [comment]
Does this type of thing work with sqlbricks themselves? Maybe the issue should be opened there?

**Comment by FanFataL** [comment]
`limit` (and other functions like `offset`) are added by this library ;-) And only those added functions not working after cloning.
The standard sql-bricks functions works perfectly after cloning.

**Comment by Suor** [comment]
Heh, it's been quite a while since I was actively developing this.
